module.exports = {
  apps: [
    {
      name: "claw-bridge",
      script: "npm",
      args: "run dev",
      cwd: "/Users/forex/openclaw-workspace/claw/bridge",
      env_file: "/Users/forex/.openclaw/mission-control/bridge.env",
      restart_delay: 5000,
      max_restarts: 10,
      autorestart: true,
      out_file: "/tmp/claw-bridge.out.log",
      error_file: "/tmp/claw-bridge.err.log",
    },
    {
      name: "claw-dashboard",
      script: "npm",
      args: "run dev",
      cwd: "/Users/forex/openclaw-workspace/claw",
      restart_delay: 5000,
      autorestart: true,
      out_file: "/tmp/claw-dashboard.out.log",
      error_file: "/tmp/claw-dashboard.err.log",
    },
    {
      name: "convex-dev",
      script: "npx",
      args: "convex dev",
      cwd: "/Users/forex/openclaw-workspace/claw",
      restart_delay: 5000,
      autorestart: true,
      out_file: "/tmp/convex-dev.out.log",
      error_file: "/tmp/convex-dev.err.log",
    },
    {
      name: "mission-tunnel",
      script: "cloudflared",
      args: "tunnel --url http://localhost:3000",
      restart_delay: 5000,
      autorestart: true,
      out_file: "/tmp/mission-tunnel.out.log",
      error_file: "/tmp/mission-tunnel.err.log",
    },
    {
      name: "gateway-tunnel",
      script: "cloudflared",
      args: "tunnel --url http://localhost:18789",
      restart_delay: 5000,
      autorestart: true,
      out_file: "/tmp/gateway-tunnel.out.log",
      error_file: "/tmp/gateway-tunnel.err.log",
    }
  ],
};
